name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v6

    - name: Test
      run: go test -v .

  integration-test:
    name: Integration Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install NFS client
      run: sudo apt-get install -y nfs-common

    - name: Integration Test
      run: sudo env "PATH=$PATH" go test -v -tags integration -run TestIntegration -timeout 120s .
